// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package uniffi.shadowmesh

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.atomic.AtomicBoolean

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.INSTANCE.ffi_shadowmesh_core_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.INSTANCE.ffi_shadowmesh_core_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len.toLong())?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

/**
 * The equivalent of the `*mut RustBuffer` type.
 * Required for callbacks taking in an out pointer.
 *
 * Size is the sum of all values in the struct.
 *
 * @suppress
 */
class RustBufferByReference : ByReference(16) {
    /**
     * Set the pointed-to `RustBuffer` to the given value.
     */
    fun setValue(value: RustBuffer.ByValue) {
        // NOTE: The offsets are as they are in the C-like struct.
        val pointer = getPointer()
        pointer.setLong(0, value.capacity)
        pointer.setLong(8, value.len)
        pointer.setPointer(16, value.data)
    }

    /**
     * Get a `RustBuffer.ByValue` from this reference.
     */
    fun getValue(): RustBuffer.ByValue {
        val pointer = getPointer()
        val value = RustBuffer.ByValue()
        value.writeField("capacity", pointer.getLong(0))
        value.writeField("len", pointer.getLong(8))
        value.writeField("data", pointer.getLong(16))

        return value
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(e.toString())
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(e.toString())
        }
    }
}
// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    private val counter = java.util.concurrent.atomic.AtomicLong(0)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(1)
        map.put(handle, obj)
        return handle
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "uniffi_shadowmesh"
}

private inline fun <reified Lib : Library> loadIndirect(
    componentName: String
): Lib {
    return Native.load<Lib>(findLibraryName(componentName), Lib::class.java)
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFuture(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureFree? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureFree? = null,
    ): UniffiForeignFuture(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFuture) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructPointer(
    @JvmField internal var `returnValue`: Pointer = Pointer.NULL,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Pointer = Pointer.NULL,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructPointer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructPointer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompletePointer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructPointer.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureStructVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructVoid.UniffiByValue,)
}






































































































// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

internal interface UniffiLib : Library {
    companion object {
        internal val INSTANCE: UniffiLib by lazy {
            loadIndirect<UniffiLib>(componentName = "shadowmesh")
            .also { lib: UniffiLib ->
                uniffiCheckContractApiVersion(lib)
                uniffiCheckApiChecksums(lib)
                }
        }
        
        // The Cleaner for the whole library
        internal val CLEANER: UniffiCleaner by lazy {
            UniffiCleaner.create()
        }
    }

    fun uniffi_shadowmesh_core_fn_clone_vpnmanager(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun uniffi_shadowmesh_core_fn_free_vpnmanager(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_shadowmesh_core_fn_method_vpnmanager_activate(`ptr`: Pointer,`code`: RustBuffer.ByValue,`token`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_shadowmesh_core_fn_method_vpnmanager_complete_connection(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_shadowmesh_core_fn_method_vpnmanager_disconnect(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_shadowmesh_core_fn_method_vpnmanager_get_best_node(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_shadowmesh_core_fn_method_vpnmanager_get_current_connection_mode(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_shadowmesh_core_fn_method_vpnmanager_get_nodes(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_shadowmesh_core_fn_method_vpnmanager_get_selected_node(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_shadowmesh_core_fn_method_vpnmanager_get_status(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_shadowmesh_core_fn_method_vpnmanager_get_user_settings(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_shadowmesh_core_fn_method_vpnmanager_initiate_connection(`ptr`: Pointer,`node`: RustBuffer.ByValue,`devicePublicKey`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_shadowmesh_core_fn_method_vpnmanager_is_activated(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun uniffi_shadowmesh_core_fn_method_vpnmanager_is_connection_timed_out(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun uniffi_shadowmesh_core_fn_method_vpnmanager_set_nodes(`ptr`: Pointer,`nodes`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_shadowmesh_core_fn_method_vpnmanager_set_selected_node(`ptr`: Pointer,`node`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_shadowmesh_core_fn_func_add(`a`: Int,`b`: Int,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    fun uniffi_shadowmesh_core_fn_func_create_vpn_manager(`settings`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun uniffi_shadowmesh_core_fn_func_generate_wireguard_keys(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_shadowmesh_core_fn_func_get_default_user_settings(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_shadowmesh_core_fn_func_get_mock_nodes(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_shadowmesh_core_fn_func_get_persistent_device_id(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_shadowmesh_core_fn_func_solve_pow(`challenge`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_shadowmesh_core_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_shadowmesh_core_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_shadowmesh_core_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun ffi_shadowmesh_core_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_shadowmesh_core_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_shadowmesh_core_rust_future_cancel_u8(`handle`: Long,
    ): Unit
    fun ffi_shadowmesh_core_rust_future_free_u8(`handle`: Long,
    ): Unit
    fun ffi_shadowmesh_core_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun ffi_shadowmesh_core_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_shadowmesh_core_rust_future_cancel_i8(`handle`: Long,
    ): Unit
    fun ffi_shadowmesh_core_rust_future_free_i8(`handle`: Long,
    ): Unit
    fun ffi_shadowmesh_core_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun ffi_shadowmesh_core_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_shadowmesh_core_rust_future_cancel_u16(`handle`: Long,
    ): Unit
    fun ffi_shadowmesh_core_rust_future_free_u16(`handle`: Long,
    ): Unit
    fun ffi_shadowmesh_core_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    fun ffi_shadowmesh_core_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_shadowmesh_core_rust_future_cancel_i16(`handle`: Long,
    ): Unit
    fun ffi_shadowmesh_core_rust_future_free_i16(`handle`: Long,
    ): Unit
    fun ffi_shadowmesh_core_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    fun ffi_shadowmesh_core_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_shadowmesh_core_rust_future_cancel_u32(`handle`: Long,
    ): Unit
    fun ffi_shadowmesh_core_rust_future_free_u32(`handle`: Long,
    ): Unit
    fun ffi_shadowmesh_core_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    fun ffi_shadowmesh_core_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_shadowmesh_core_rust_future_cancel_i32(`handle`: Long,
    ): Unit
    fun ffi_shadowmesh_core_rust_future_free_i32(`handle`: Long,
    ): Unit
    fun ffi_shadowmesh_core_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    fun ffi_shadowmesh_core_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_shadowmesh_core_rust_future_cancel_u64(`handle`: Long,
    ): Unit
    fun ffi_shadowmesh_core_rust_future_free_u64(`handle`: Long,
    ): Unit
    fun ffi_shadowmesh_core_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    fun ffi_shadowmesh_core_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_shadowmesh_core_rust_future_cancel_i64(`handle`: Long,
    ): Unit
    fun ffi_shadowmesh_core_rust_future_free_i64(`handle`: Long,
    ): Unit
    fun ffi_shadowmesh_core_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    fun ffi_shadowmesh_core_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_shadowmesh_core_rust_future_cancel_f32(`handle`: Long,
    ): Unit
    fun ffi_shadowmesh_core_rust_future_free_f32(`handle`: Long,
    ): Unit
    fun ffi_shadowmesh_core_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Float
    fun ffi_shadowmesh_core_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_shadowmesh_core_rust_future_cancel_f64(`handle`: Long,
    ): Unit
    fun ffi_shadowmesh_core_rust_future_free_f64(`handle`: Long,
    ): Unit
    fun ffi_shadowmesh_core_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Double
    fun ffi_shadowmesh_core_rust_future_poll_pointer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_shadowmesh_core_rust_future_cancel_pointer(`handle`: Long,
    ): Unit
    fun ffi_shadowmesh_core_rust_future_free_pointer(`handle`: Long,
    ): Unit
    fun ffi_shadowmesh_core_rust_future_complete_pointer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun ffi_shadowmesh_core_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_shadowmesh_core_rust_future_cancel_rust_buffer(`handle`: Long,
    ): Unit
    fun ffi_shadowmesh_core_rust_future_free_rust_buffer(`handle`: Long,
    ): Unit
    fun ffi_shadowmesh_core_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_shadowmesh_core_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_shadowmesh_core_rust_future_cancel_void(`handle`: Long,
    ): Unit
    fun ffi_shadowmesh_core_rust_future_free_void(`handle`: Long,
    ): Unit
    fun ffi_shadowmesh_core_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_shadowmesh_core_checksum_func_add(
    ): Short
    fun uniffi_shadowmesh_core_checksum_func_create_vpn_manager(
    ): Short
    fun uniffi_shadowmesh_core_checksum_func_generate_wireguard_keys(
    ): Short
    fun uniffi_shadowmesh_core_checksum_func_get_default_user_settings(
    ): Short
    fun uniffi_shadowmesh_core_checksum_func_get_mock_nodes(
    ): Short
    fun uniffi_shadowmesh_core_checksum_func_get_persistent_device_id(
    ): Short
    fun uniffi_shadowmesh_core_checksum_func_solve_pow(
    ): Short
    fun uniffi_shadowmesh_core_checksum_method_vpnmanager_activate(
    ): Short
    fun uniffi_shadowmesh_core_checksum_method_vpnmanager_complete_connection(
    ): Short
    fun uniffi_shadowmesh_core_checksum_method_vpnmanager_disconnect(
    ): Short
    fun uniffi_shadowmesh_core_checksum_method_vpnmanager_get_best_node(
    ): Short
    fun uniffi_shadowmesh_core_checksum_method_vpnmanager_get_current_connection_mode(
    ): Short
    fun uniffi_shadowmesh_core_checksum_method_vpnmanager_get_nodes(
    ): Short
    fun uniffi_shadowmesh_core_checksum_method_vpnmanager_get_selected_node(
    ): Short
    fun uniffi_shadowmesh_core_checksum_method_vpnmanager_get_status(
    ): Short
    fun uniffi_shadowmesh_core_checksum_method_vpnmanager_get_user_settings(
    ): Short
    fun uniffi_shadowmesh_core_checksum_method_vpnmanager_initiate_connection(
    ): Short
    fun uniffi_shadowmesh_core_checksum_method_vpnmanager_is_activated(
    ): Short
    fun uniffi_shadowmesh_core_checksum_method_vpnmanager_is_connection_timed_out(
    ): Short
    fun uniffi_shadowmesh_core_checksum_method_vpnmanager_set_nodes(
    ): Short
    fun uniffi_shadowmesh_core_checksum_method_vpnmanager_set_selected_node(
    ): Short
    fun ffi_shadowmesh_core_uniffi_contract_version(
    ): Int
    
}

private fun uniffiCheckContractApiVersion(lib: UniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_shadowmesh_core_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}

@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: UniffiLib) {
    if (lib.uniffi_shadowmesh_core_checksum_func_add() != 43874.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_shadowmesh_core_checksum_func_create_vpn_manager() != 21088.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_shadowmesh_core_checksum_func_generate_wireguard_keys() != 60089.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_shadowmesh_core_checksum_func_get_default_user_settings() != 14582.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_shadowmesh_core_checksum_func_get_mock_nodes() != 15589.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_shadowmesh_core_checksum_func_get_persistent_device_id() != 15672.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_shadowmesh_core_checksum_func_solve_pow() != 21141.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_shadowmesh_core_checksum_method_vpnmanager_activate() != 43822.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_shadowmesh_core_checksum_method_vpnmanager_complete_connection() != 14322.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_shadowmesh_core_checksum_method_vpnmanager_disconnect() != 57487.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_shadowmesh_core_checksum_method_vpnmanager_get_best_node() != 51201.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_shadowmesh_core_checksum_method_vpnmanager_get_current_connection_mode() != 61754.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_shadowmesh_core_checksum_method_vpnmanager_get_nodes() != 15897.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_shadowmesh_core_checksum_method_vpnmanager_get_selected_node() != 47044.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_shadowmesh_core_checksum_method_vpnmanager_get_status() != 22575.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_shadowmesh_core_checksum_method_vpnmanager_get_user_settings() != 7670.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_shadowmesh_core_checksum_method_vpnmanager_initiate_connection() != 16645.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_shadowmesh_core_checksum_method_vpnmanager_is_activated() != 21727.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_shadowmesh_core_checksum_method_vpnmanager_is_connection_timed_out() != 42004.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_shadowmesh_core_checksum_method_vpnmanager_set_nodes() != 2503.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_shadowmesh_core_checksum_method_vpnmanager_set_selected_node() != 21358.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            args.filterIsInstance<Disposable>()
                .forEach(Disposable::destroy)
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/** 
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoPointer

/**
 * @suppress
 */
public object FfiConverterUInt: FfiConverter<UInt, Int> {
    override fun lift(value: Int): UInt {
        return value.toUInt()
    }

    override fun read(buf: ByteBuffer): UInt {
        return lift(buf.getInt())
    }

    override fun lower(value: UInt): Int {
        return value.toInt()
    }

    override fun allocationSize(value: UInt) = 4UL

    override fun write(value: UInt, buf: ByteBuffer) {
        buf.putInt(value.toInt())
    }
}

/**
 * @suppress
 */
public object FfiConverterULong: FfiConverter<ULong, Long> {
    override fun lift(value: Long): ULong {
        return value.toULong()
    }

    override fun read(buf: ByteBuffer): ULong {
        return lift(buf.getLong())
    }

    override fun lower(value: ULong): Long {
        return value.toLong()
    }

    override fun allocationSize(value: ULong) = 8UL

    override fun write(value: ULong, buf: ByteBuffer) {
        buf.putLong(value.toLong())
    }
}

/**
 * @suppress
 */
public object FfiConverterLong: FfiConverter<Long, Long> {
    override fun lift(value: Long): Long {
        return value
    }

    override fun read(buf: ByteBuffer): Long {
        return buf.getLong()
    }

    override fun lower(value: Long): Long {
        return value
    }

    override fun allocationSize(value: Long) = 8UL

    override fun write(value: Long, buf: ByteBuffer) {
        buf.putLong(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterDouble: FfiConverter<Double, Double> {
    override fun lift(value: Double): Double {
        return value
    }

    override fun read(buf: ByteBuffer): Double {
        return buf.getDouble()
    }

    override fun lower(value: Double): Double {
        return value
    }

    override fun allocationSize(value: Double) = 8UL

    override fun write(value: Double, buf: ByteBuffer) {
        buf.putDouble(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1UL

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}


// This template implements a class for working with a Rust struct via a Pointer/Arc<T>
// to the live Rust struct on the other side of the FFI.
//
// Each instance implements core operations for working with the Rust `Arc<T>` and the
// Kotlin Pointer to work with the live Rust struct on the other side of the FFI.
//
// There's some subtlety here, because we have to be careful not to operate on a Rust
// struct after it has been dropped, and because we must expose a public API for freeing
// theq Kotlin wrapper object in lieu of reliable finalizers. The core requirements are:
//
//   * Each instance holds an opaque pointer to the underlying Rust struct.
//     Method calls need to read this pointer from the object's state and pass it in to
//     the Rust FFI.
//
//   * When an instance is no longer needed, its pointer should be passed to a
//     special destructor function provided by the Rust FFI, which will drop the
//     underlying Rust struct.
//
//   * Given an instance, calling code is expected to call the special
//     `destroy` method in order to free it after use, either by calling it explicitly
//     or by using a higher-level helper like the `use` method. Failing to do so risks
//     leaking the underlying Rust struct.
//
//   * We can't assume that calling code will do the right thing, and must be prepared
//     to handle Kotlin method calls executing concurrently with or even after a call to
//     `destroy`, and to handle multiple (possibly concurrent!) calls to `destroy`.
//
//   * We must never allow Rust code to operate on the underlying Rust struct after
//     the destructor has been called, and must never call the destructor more than once.
//     Doing so may trigger memory unsafety.
//
//   * To mitigate many of the risks of leaking memory and use-after-free unsafety, a `Cleaner`
//     is implemented to call the destructor when the Kotlin object becomes unreachable.
//     This is done in a background thread. This is not a panacea, and client code should be aware that
//      1. the thread may starve if some there are objects that have poorly performing
//     `drop` methods or do significant work in their `drop` methods.
//      2. the thread is shared across the whole library. This can be tuned by using `android_cleaner = true`,
//         or `android = true` in the [`kotlin` section of the `uniffi.toml` file](https://mozilla.github.io/uniffi-rs/kotlin/configuration.html).
//
// If we try to implement this with mutual exclusion on access to the pointer, there is the
// possibility of a race between a method call and a concurrent call to `destroy`:
//
//    * Thread A starts a method call, reads the value of the pointer, but is interrupted
//      before it can pass the pointer over the FFI to Rust.
//    * Thread B calls `destroy` and frees the underlying Rust struct.
//    * Thread A resumes, passing the already-read pointer value to Rust and triggering
//      a use-after-free.
//
// One possible solution would be to use a `ReadWriteLock`, with each method call taking
// a read lock (and thus allowed to run concurrently) and the special `destroy` method
// taking a write lock (and thus blocking on live method calls). However, we aim not to
// generate methods with any hidden blocking semantics, and a `destroy` method that might
// block if called incorrectly seems to meet that bar.
//
// So, we achieve our goals by giving each instance an associated `AtomicLong` counter to track
// the number of in-flight method calls, and an `AtomicBoolean` flag to indicate whether `destroy`
// has been called. These are updated according to the following rules:
//
//    * The initial value of the counter is 1, indicating a live object with no in-flight calls.
//      The initial value for the flag is false.
//
//    * At the start of each method call, we atomically check the counter.
//      If it is 0 then the underlying Rust struct has already been destroyed and the call is aborted.
//      If it is nonzero them we atomically increment it by 1 and proceed with the method call.
//
//    * At the end of each method call, we atomically decrement and check the counter.
//      If it has reached zero then we destroy the underlying Rust struct.
//
//    * When `destroy` is called, we atomically flip the flag from false to true.
//      If the flag was already true we silently fail.
//      Otherwise we atomically decrement and check the counter.
//      If it has reached zero then we destroy the underlying Rust struct.
//
// Astute readers may observe that this all sounds very similar to the way that Rust's `Arc<T>` works,
// and indeed it is, with the addition of a flag to guard against multiple calls to `destroy`.
//
// The overall effect is that the underlying Rust struct is destroyed only when `destroy` has been
// called *and* all in-flight method calls have completed, avoiding violating any of the expectations
// of the underlying Rust code.
//
// This makes a cleaner a better alternative to _not_ calling `destroy()` as
// and when the object is finished with, but the abstraction is not perfect: if the Rust object's `drop`
// method is slow, and/or there are many objects to cleanup, and it's on a low end Android device, then the cleaner
// thread may be starved, and the app will leak memory.
//
// In this case, `destroy`ing manually may be a better solution.
//
// The cleaner can live side by side with the manual calling of `destroy`. In the order of responsiveness, uniffi objects
// with Rust peers are reclaimed:
//
// 1. By calling the `destroy` method of the object, which calls `rustObject.free()`. If that doesn't happen:
// 2. When the object becomes unreachable, AND the Cleaner thread gets to call `rustObject.free()`. If the thread is starved then:
// 3. The memory is reclaimed when the process terminates.
//
// [1] https://stackoverflow.com/questions/24376768/can-java-finalize-an-object-when-it-is-still-in-scope/24380219
//


/**
 * The cleaner interface for Object finalization code to run.
 * This is the entry point to any implementation that we're using.
 *
 * The cleaner registers objects and returns cleanables, so now we are
 * defining a `UniffiCleaner` with a `UniffiClenaer.Cleanable` to abstract the
 * different implmentations available at compile time.
 *
 * @suppress
 */
interface UniffiCleaner {
    interface Cleanable {
        fun clean()
    }

    fun register(value: Any, cleanUpTask: Runnable): UniffiCleaner.Cleanable

    companion object
}

// The fallback Jna cleaner, which is available for both Android, and the JVM.
private class UniffiJnaCleaner : UniffiCleaner {
    private val cleaner = com.sun.jna.internal.Cleaner.getCleaner()

    override fun register(value: Any, cleanUpTask: Runnable): UniffiCleaner.Cleanable =
        UniffiJnaCleanable(cleaner.register(value, cleanUpTask))
}

private class UniffiJnaCleanable(
    private val cleanable: com.sun.jna.internal.Cleaner.Cleanable,
) : UniffiCleaner.Cleanable {
    override fun clean() = cleanable.clean()
}

// We decide at uniffi binding generation time whether we were
// using Android or not.
// There are further runtime checks to chose the correct implementation
// of the cleaner.
private fun UniffiCleaner.Companion.create(): UniffiCleaner =
    try {
        // For safety's sake: if the library hasn't been run in android_cleaner = true
        // mode, but is being run on Android, then we still need to think about
        // Android API versions.
        // So we check if java.lang.ref.Cleaner is there, and use that…
        java.lang.Class.forName("java.lang.ref.Cleaner")
        JavaLangRefCleaner()
    } catch (e: ClassNotFoundException) {
        // … otherwise, fallback to the JNA cleaner.
        UniffiJnaCleaner()
    }

private class JavaLangRefCleaner : UniffiCleaner {
    val cleaner = java.lang.ref.Cleaner.create()

    override fun register(value: Any, cleanUpTask: Runnable): UniffiCleaner.Cleanable =
        JavaLangRefCleanable(cleaner.register(value, cleanUpTask))
}

private class JavaLangRefCleanable(
    val cleanable: java.lang.ref.Cleaner.Cleanable
) : UniffiCleaner.Cleanable {
    override fun clean() = cleanable.clean()
}
public interface VpnManagerInterface {
    
    fun `activate`(`code`: kotlin.String, `token`: kotlin.String?)
    
    fun `completeConnection`()
    
    fun `disconnect`()
    
    fun `getBestNode`(): VpnNode?
    
    fun `getCurrentConnectionMode`(): TrafficMode?
    
    fun `getNodes`(): List<VpnNode>
    
    fun `getSelectedNode`(): VpnNode?
    
    fun `getStatus`(): ConnectionStatus
    
    fun `getUserSettings`(): UserSettings
    
    fun `initiateConnection`(`node`: VpnNode, `devicePublicKey`: kotlin.String)
    
    fun `isActivated`(): kotlin.Boolean
    
    fun `isConnectionTimedOut`(): kotlin.Boolean
    
    fun `setNodes`(`nodes`: List<VpnNode>)
    
    fun `setSelectedNode`(`node`: VpnNode)
    
    companion object
}

open class VpnManager: Disposable, AutoCloseable, VpnManagerInterface {

    constructor(pointer: Pointer) {
        this.pointer = pointer
        this.cleanable = UniffiLib.CLEANER.register(this, UniffiCleanAction(pointer))
    }

    /**
     * This constructor can be used to instantiate a fake object. Only used for tests. Any
     * attempt to actually use an object constructed this way will fail as there is no
     * connected Rust object.
     */
    @Suppress("UNUSED_PARAMETER")
    constructor(noPointer: NoPointer) {
        this.pointer = null
        this.cleanable = UniffiLib.CLEANER.register(this, UniffiCleanAction(pointer))
    }

    protected val pointer: Pointer?
    protected val cleanable: UniffiCleaner.Cleanable

    private val wasDestroyed = AtomicBoolean(false)
    private val callCounter = AtomicLong(1)

    override fun destroy() {
        // Only allow a single call to this method.
        // TODO: maybe we should log a warning if called more than once?
        if (this.wasDestroyed.compareAndSet(false, true)) {
            // This decrement always matches the initial count of 1 given at creation time.
            if (this.callCounter.decrementAndGet() == 0L) {
                cleanable.clean()
            }
        }
    }

    @Synchronized
    override fun close() {
        this.destroy()
    }

    internal inline fun <R> callWithPointer(block: (ptr: Pointer) -> R): R {
        // Check and increment the call counter, to keep the object alive.
        // This needs a compare-and-set retry loop in case of concurrent updates.
        do {
            val c = this.callCounter.get()
            if (c == 0L) {
                throw IllegalStateException("${this.javaClass.simpleName} object has already been destroyed")
            }
            if (c == Long.MAX_VALUE) {
                throw IllegalStateException("${this.javaClass.simpleName} call counter would overflow")
            }
        } while (! this.callCounter.compareAndSet(c, c + 1L))
        // Now we can safely do the method call without the pointer being freed concurrently.
        try {
            return block(this.uniffiClonePointer())
        } finally {
            // This decrement always matches the increment we performed above.
            if (this.callCounter.decrementAndGet() == 0L) {
                cleanable.clean()
            }
        }
    }

    // Use a static inner class instead of a closure so as not to accidentally
    // capture `this` as part of the cleanable's action.
    private class UniffiCleanAction(private val pointer: Pointer?) : Runnable {
        override fun run() {
            pointer?.let { ptr ->
                uniffiRustCall { status ->
                    UniffiLib.INSTANCE.uniffi_shadowmesh_core_fn_free_vpnmanager(ptr, status)
                }
            }
        }
    }

    fun uniffiClonePointer(): Pointer {
        return uniffiRustCall() { status ->
            UniffiLib.INSTANCE.uniffi_shadowmesh_core_fn_clone_vpnmanager(pointer!!, status)
        }
    }

    
    @Throws(ShadowMeshException::class)override fun `activate`(`code`: kotlin.String, `token`: kotlin.String?)
        = 
    callWithPointer {
    uniffiRustCallWithError(ShadowMeshException) { _status ->
    UniffiLib.INSTANCE.uniffi_shadowmesh_core_fn_method_vpnmanager_activate(
        it, FfiConverterString.lower(`code`),FfiConverterOptionalString.lower(`token`),_status)
}
    }
    
    

    override fun `completeConnection`()
        = 
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_shadowmesh_core_fn_method_vpnmanager_complete_connection(
        it, _status)
}
    }
    
    

    override fun `disconnect`()
        = 
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_shadowmesh_core_fn_method_vpnmanager_disconnect(
        it, _status)
}
    }
    
    

    override fun `getBestNode`(): VpnNode? {
            return FfiConverterOptionalTypeVPNNode.lift(
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_shadowmesh_core_fn_method_vpnmanager_get_best_node(
        it, _status)
}
    }
    )
    }
    

    override fun `getCurrentConnectionMode`(): TrafficMode? {
            return FfiConverterOptionalTypeTrafficMode.lift(
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_shadowmesh_core_fn_method_vpnmanager_get_current_connection_mode(
        it, _status)
}
    }
    )
    }
    

    override fun `getNodes`(): List<VpnNode> {
            return FfiConverterSequenceTypeVPNNode.lift(
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_shadowmesh_core_fn_method_vpnmanager_get_nodes(
        it, _status)
}
    }
    )
    }
    

    override fun `getSelectedNode`(): VpnNode? {
            return FfiConverterOptionalTypeVPNNode.lift(
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_shadowmesh_core_fn_method_vpnmanager_get_selected_node(
        it, _status)
}
    }
    )
    }
    

    override fun `getStatus`(): ConnectionStatus {
            return FfiConverterTypeConnectionStatus.lift(
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_shadowmesh_core_fn_method_vpnmanager_get_status(
        it, _status)
}
    }
    )
    }
    

    override fun `getUserSettings`(): UserSettings {
            return FfiConverterTypeUserSettings.lift(
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_shadowmesh_core_fn_method_vpnmanager_get_user_settings(
        it, _status)
}
    }
    )
    }
    

    
    @Throws(ShadowMeshException::class)override fun `initiateConnection`(`node`: VpnNode, `devicePublicKey`: kotlin.String)
        = 
    callWithPointer {
    uniffiRustCallWithError(ShadowMeshException) { _status ->
    UniffiLib.INSTANCE.uniffi_shadowmesh_core_fn_method_vpnmanager_initiate_connection(
        it, FfiConverterTypeVPNNode.lower(`node`),FfiConverterString.lower(`devicePublicKey`),_status)
}
    }
    
    

    override fun `isActivated`(): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_shadowmesh_core_fn_method_vpnmanager_is_activated(
        it, _status)
}
    }
    )
    }
    

    override fun `isConnectionTimedOut`(): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_shadowmesh_core_fn_method_vpnmanager_is_connection_timed_out(
        it, _status)
}
    }
    )
    }
    

    override fun `setNodes`(`nodes`: List<VpnNode>)
        = 
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_shadowmesh_core_fn_method_vpnmanager_set_nodes(
        it, FfiConverterSequenceTypeVPNNode.lower(`nodes`),_status)
}
    }
    
    

    override fun `setSelectedNode`(`node`: VpnNode)
        = 
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_shadowmesh_core_fn_method_vpnmanager_set_selected_node(
        it, FfiConverterTypeVPNNode.lower(`node`),_status)
}
    }
    
    

    

    
    
    companion object
    
}

/**
 * @suppress
 */
public object FfiConverterTypeVPNManager: FfiConverter<VpnManager, Pointer> {

    override fun lower(value: VpnManager): Pointer {
        return value.uniffiClonePointer()
    }

    override fun lift(value: Pointer): VpnManager {
        return VpnManager(value)
    }

    override fun read(buf: ByteBuffer): VpnManager {
        // The Rust code always writes pointers as 8 bytes, and will
        // fail to compile if they don't fit.
        return lift(Pointer(buf.getLong()))
    }

    override fun allocationSize(value: VpnManager) = 8UL

    override fun write(value: VpnManager, buf: ByteBuffer) {
        // The Rust code always expects pointers written as 8 bytes,
        // and will fail to compile if they don't fit.
        buf.putLong(Pointer.nativeValue(lower(value)))
    }
}



data class ActivationChallenge (
    var `nonce`: kotlin.String, 
    var `difficulty`: kotlin.UInt, 
    var `timestamp`: kotlin.Long, 
    var `signature`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeActivationChallenge: FfiConverterRustBuffer<ActivationChallenge> {
    override fun read(buf: ByteBuffer): ActivationChallenge {
        return ActivationChallenge(
            FfiConverterString.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterLong.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: ActivationChallenge) = (
            FfiConverterString.allocationSize(value.`nonce`) +
            FfiConverterUInt.allocationSize(value.`difficulty`) +
            FfiConverterLong.allocationSize(value.`timestamp`) +
            FfiConverterString.allocationSize(value.`signature`)
    )

    override fun write(value: ActivationChallenge, buf: ByteBuffer) {
            FfiConverterString.write(value.`nonce`, buf)
            FfiConverterUInt.write(value.`difficulty`, buf)
            FfiConverterLong.write(value.`timestamp`, buf)
            FfiConverterString.write(value.`signature`, buf)
    }
}



data class ActivationRequest (
    var `activationCode`: kotlin.String, 
    var `deviceId`: kotlin.String, 
    var `solution`: kotlin.String, 
    var `nonce`: kotlin.String, 
    var `timestamp`: kotlin.Long, 
    var `signature`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeActivationRequest: FfiConverterRustBuffer<ActivationRequest> {
    override fun read(buf: ByteBuffer): ActivationRequest {
        return ActivationRequest(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterLong.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: ActivationRequest) = (
            FfiConverterString.allocationSize(value.`activationCode`) +
            FfiConverterString.allocationSize(value.`deviceId`) +
            FfiConverterString.allocationSize(value.`solution`) +
            FfiConverterString.allocationSize(value.`nonce`) +
            FfiConverterLong.allocationSize(value.`timestamp`) +
            FfiConverterString.allocationSize(value.`signature`)
    )

    override fun write(value: ActivationRequest, buf: ByteBuffer) {
            FfiConverterString.write(value.`activationCode`, buf)
            FfiConverterString.write(value.`deviceId`, buf)
            FfiConverterString.write(value.`solution`, buf)
            FfiConverterString.write(value.`nonce`, buf)
            FfiConverterLong.write(value.`timestamp`, buf)
            FfiConverterString.write(value.`signature`, buf)
    }
}



data class ActivationResponse (
    var `success`: kotlin.Boolean, 
    var `authToken`: kotlin.String?, 
    var `message`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeActivationResponse: FfiConverterRustBuffer<ActivationResponse> {
    override fun read(buf: ByteBuffer): ActivationResponse {
        return ActivationResponse(
            FfiConverterBoolean.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: ActivationResponse) = (
            FfiConverterBoolean.allocationSize(value.`success`) +
            FfiConverterOptionalString.allocationSize(value.`authToken`) +
            FfiConverterString.allocationSize(value.`message`)
    )

    override fun write(value: ActivationResponse, buf: ByteBuffer) {
            FfiConverterBoolean.write(value.`success`, buf)
            FfiConverterOptionalString.write(value.`authToken`, buf)
            FfiConverterString.write(value.`message`, buf)
    }
}



data class ConnectionStats (
    var `bytesReceived`: kotlin.ULong, 
    var `bytesSent`: kotlin.ULong, 
    var `packetsReceived`: kotlin.ULong, 
    var `packetsSent`: kotlin.ULong, 
    var `lastHandshake`: kotlin.Long, 
    var `connectedSince`: kotlin.Long
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeConnectionStats: FfiConverterRustBuffer<ConnectionStats> {
    override fun read(buf: ByteBuffer): ConnectionStats {
        return ConnectionStats(
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterLong.read(buf),
            FfiConverterLong.read(buf),
        )
    }

    override fun allocationSize(value: ConnectionStats) = (
            FfiConverterULong.allocationSize(value.`bytesReceived`) +
            FfiConverterULong.allocationSize(value.`bytesSent`) +
            FfiConverterULong.allocationSize(value.`packetsReceived`) +
            FfiConverterULong.allocationSize(value.`packetsSent`) +
            FfiConverterLong.allocationSize(value.`lastHandshake`) +
            FfiConverterLong.allocationSize(value.`connectedSince`)
    )

    override fun write(value: ConnectionStats, buf: ByteBuffer) {
            FfiConverterULong.write(value.`bytesReceived`, buf)
            FfiConverterULong.write(value.`bytesSent`, buf)
            FfiConverterULong.write(value.`packetsReceived`, buf)
            FfiConverterULong.write(value.`packetsSent`, buf)
            FfiConverterLong.write(value.`lastHandshake`, buf)
            FfiConverterLong.write(value.`connectedSince`, buf)
    }
}



data class PoWChallenge (
    var `nonce`: kotlin.String, 
    var `difficulty`: kotlin.UInt, 
    var `timestamp`: kotlin.Long, 
    var `signature`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypePoWChallenge: FfiConverterRustBuffer<PoWChallenge> {
    override fun read(buf: ByteBuffer): PoWChallenge {
        return PoWChallenge(
            FfiConverterString.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterLong.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: PoWChallenge) = (
            FfiConverterString.allocationSize(value.`nonce`) +
            FfiConverterUInt.allocationSize(value.`difficulty`) +
            FfiConverterLong.allocationSize(value.`timestamp`) +
            FfiConverterString.allocationSize(value.`signature`)
    )

    override fun write(value: PoWChallenge, buf: ByteBuffer) {
            FfiConverterString.write(value.`nonce`, buf)
            FfiConverterUInt.write(value.`difficulty`, buf)
            FfiConverterLong.write(value.`timestamp`, buf)
            FfiConverterString.write(value.`signature`, buf)
    }
}



data class PoWSolution (
    var `solution`: kotlin.String, 
    var `nonce`: kotlin.String, 
    var `timestamp`: kotlin.Long, 
    var `signature`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypePoWSolution: FfiConverterRustBuffer<PoWSolution> {
    override fun read(buf: ByteBuffer): PoWSolution {
        return PoWSolution(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterLong.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: PoWSolution) = (
            FfiConverterString.allocationSize(value.`solution`) +
            FfiConverterString.allocationSize(value.`nonce`) +
            FfiConverterLong.allocationSize(value.`timestamp`) +
            FfiConverterString.allocationSize(value.`signature`)
    )

    override fun write(value: PoWSolution, buf: ByteBuffer) {
            FfiConverterString.write(value.`solution`, buf)
            FfiConverterString.write(value.`nonce`, buf)
            FfiConverterLong.write(value.`timestamp`, buf)
            FfiConverterString.write(value.`signature`, buf)
    }
}



data class SplitTunnelConfig (
    var `enabled`: kotlin.Boolean, 
    var `mode`: kotlin.String, 
    var `appList`: List<kotlin.String>
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeSplitTunnelConfig: FfiConverterRustBuffer<SplitTunnelConfig> {
    override fun read(buf: ByteBuffer): SplitTunnelConfig {
        return SplitTunnelConfig(
            FfiConverterBoolean.read(buf),
            FfiConverterString.read(buf),
            FfiConverterSequenceString.read(buf),
        )
    }

    override fun allocationSize(value: SplitTunnelConfig) = (
            FfiConverterBoolean.allocationSize(value.`enabled`) +
            FfiConverterString.allocationSize(value.`mode`) +
            FfiConverterSequenceString.allocationSize(value.`appList`)
    )

    override fun write(value: SplitTunnelConfig, buf: ByteBuffer) {
            FfiConverterBoolean.write(value.`enabled`, buf)
            FfiConverterString.write(value.`mode`, buf)
            FfiConverterSequenceString.write(value.`appList`, buf)
    }
}



data class UserSettings (
    var `killSwitchEnabled`: kotlin.Boolean, 
    var `dnsLeakProtection`: kotlin.Boolean, 
    var `emergencyRecoveryEnabled`: kotlin.Boolean, 
    var `dnsServers`: List<kotlin.String>
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeUserSettings: FfiConverterRustBuffer<UserSettings> {
    override fun read(buf: ByteBuffer): UserSettings {
        return UserSettings(
            FfiConverterBoolean.read(buf),
            FfiConverterBoolean.read(buf),
            FfiConverterBoolean.read(buf),
            FfiConverterSequenceString.read(buf),
        )
    }

    override fun allocationSize(value: UserSettings) = (
            FfiConverterBoolean.allocationSize(value.`killSwitchEnabled`) +
            FfiConverterBoolean.allocationSize(value.`dnsLeakProtection`) +
            FfiConverterBoolean.allocationSize(value.`emergencyRecoveryEnabled`) +
            FfiConverterSequenceString.allocationSize(value.`dnsServers`)
    )

    override fun write(value: UserSettings, buf: ByteBuffer) {
            FfiConverterBoolean.write(value.`killSwitchEnabled`, buf)
            FfiConverterBoolean.write(value.`dnsLeakProtection`, buf)
            FfiConverterBoolean.write(value.`emergencyRecoveryEnabled`, buf)
            FfiConverterSequenceString.write(value.`dnsServers`, buf)
    }
}



data class VpnConfig (
    var `privateKey`: kotlin.String, 
    var `publicKey`: kotlin.String, 
    var `address`: kotlin.String, 
    var `dns`: List<kotlin.String>, 
    var `mtu`: kotlin.UInt
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeVPNConfig: FfiConverterRustBuffer<VpnConfig> {
    override fun read(buf: ByteBuffer): VpnConfig {
        return VpnConfig(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterSequenceString.read(buf),
            FfiConverterUInt.read(buf),
        )
    }

    override fun allocationSize(value: VpnConfig) = (
            FfiConverterString.allocationSize(value.`privateKey`) +
            FfiConverterString.allocationSize(value.`publicKey`) +
            FfiConverterString.allocationSize(value.`address`) +
            FfiConverterSequenceString.allocationSize(value.`dns`) +
            FfiConverterUInt.allocationSize(value.`mtu`)
    )

    override fun write(value: VpnConfig, buf: ByteBuffer) {
            FfiConverterString.write(value.`privateKey`, buf)
            FfiConverterString.write(value.`publicKey`, buf)
            FfiConverterString.write(value.`address`, buf)
            FfiConverterSequenceString.write(value.`dns`, buf)
            FfiConverterUInt.write(value.`mtu`, buf)
    }
}



data class VpnNode (
    var `id`: kotlin.String, 
    var `name`: kotlin.String, 
    var `region`: kotlin.String, 
    var `country`: kotlin.String, 
    var `endpoint`: kotlin.String, 
    var `publicKey`: kotlin.String, 
    var `load`: kotlin.UInt, 
    var `latency`: kotlin.Double
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeVPNNode: FfiConverterRustBuffer<VpnNode> {
    override fun read(buf: ByteBuffer): VpnNode {
        return VpnNode(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterDouble.read(buf),
        )
    }

    override fun allocationSize(value: VpnNode) = (
            FfiConverterString.allocationSize(value.`id`) +
            FfiConverterString.allocationSize(value.`name`) +
            FfiConverterString.allocationSize(value.`region`) +
            FfiConverterString.allocationSize(value.`country`) +
            FfiConverterString.allocationSize(value.`endpoint`) +
            FfiConverterString.allocationSize(value.`publicKey`) +
            FfiConverterUInt.allocationSize(value.`load`) +
            FfiConverterDouble.allocationSize(value.`latency`)
    )

    override fun write(value: VpnNode, buf: ByteBuffer) {
            FfiConverterString.write(value.`id`, buf)
            FfiConverterString.write(value.`name`, buf)
            FfiConverterString.write(value.`region`, buf)
            FfiConverterString.write(value.`country`, buf)
            FfiConverterString.write(value.`endpoint`, buf)
            FfiConverterString.write(value.`publicKey`, buf)
            FfiConverterUInt.write(value.`load`, buf)
            FfiConverterDouble.write(value.`latency`, buf)
    }
}




enum class ConnectionStatus {
    
    DISCONNECTED,
    CONNECTING_DIRECT,
    CONNECTING_FRAGMENTED,
    CONNECTING_REALITY,
    CONNECTED,
    DISCONNECTING,
    ERROR;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeConnectionStatus: FfiConverterRustBuffer<ConnectionStatus> {
    override fun read(buf: ByteBuffer) = try {
        ConnectionStatus.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: ConnectionStatus) = 4UL

    override fun write(value: ConnectionStatus, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}







sealed class ShadowMeshException(message: String): kotlin.Exception(message) {
        
        class KeyGenerationFailed(message: String) : ShadowMeshException(message)
        
        class PowTimeout(message: String) : ShadowMeshException(message)
        
        class ConnectionFailed(message: String) : ShadowMeshException(message)
        
        class NodeNotFound(message: String) : ShadowMeshException(message)
        
        class Other(message: String) : ShadowMeshException(message)
        

    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<ShadowMeshException> {
        override fun lift(error_buf: RustBuffer.ByValue): ShadowMeshException = FfiConverterTypeShadowMeshError.lift(error_buf)
    }
}

/**
 * @suppress
 */
public object FfiConverterTypeShadowMeshError : FfiConverterRustBuffer<ShadowMeshException> {
    override fun read(buf: ByteBuffer): ShadowMeshException {
        
            return when(buf.getInt()) {
            1 -> ShadowMeshException.KeyGenerationFailed(FfiConverterString.read(buf))
            2 -> ShadowMeshException.PowTimeout(FfiConverterString.read(buf))
            3 -> ShadowMeshException.ConnectionFailed(FfiConverterString.read(buf))
            4 -> ShadowMeshException.NodeNotFound(FfiConverterString.read(buf))
            5 -> ShadowMeshException.Other(FfiConverterString.read(buf))
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
        
    }

    override fun allocationSize(value: ShadowMeshException): ULong {
        return 4UL
    }

    override fun write(value: ShadowMeshException, buf: ByteBuffer) {
        when(value) {
            is ShadowMeshException.KeyGenerationFailed -> {
                buf.putInt(1)
                Unit
            }
            is ShadowMeshException.PowTimeout -> {
                buf.putInt(2)
                Unit
            }
            is ShadowMeshException.ConnectionFailed -> {
                buf.putInt(3)
                Unit
            }
            is ShadowMeshException.NodeNotFound -> {
                buf.putInt(4)
                Unit
            }
            is ShadowMeshException.Other -> {
                buf.putInt(5)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}




enum class TrafficMode {
    
    NORMAL,
    FRAGMENTED,
    REALITY;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeTrafficMode: FfiConverterRustBuffer<TrafficMode> {
    override fun read(buf: ByteBuffer) = try {
        TrafficMode.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: TrafficMode) = 4UL

    override fun write(value: TrafficMode, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






enum class TrafficModePreference {
    
    AUTO,
    SPEED,
    STEALTH;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeTrafficModePreference: FfiConverterRustBuffer<TrafficModePreference> {
    override fun read(buf: ByteBuffer) = try {
        TrafficModePreference.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: TrafficModePreference) = 4UL

    override fun write(value: TrafficModePreference, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






/**
 * @suppress
 */
public object FfiConverterOptionalString: FfiConverterRustBuffer<kotlin.String?> {
    override fun read(buf: ByteBuffer): kotlin.String? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterString.read(buf)
    }

    override fun allocationSize(value: kotlin.String?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterString.allocationSize(value)
        }
    }

    override fun write(value: kotlin.String?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterString.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypeVPNNode: FfiConverterRustBuffer<VpnNode?> {
    override fun read(buf: ByteBuffer): VpnNode? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeVPNNode.read(buf)
    }

    override fun allocationSize(value: VpnNode?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeVPNNode.allocationSize(value)
        }
    }

    override fun write(value: VpnNode?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeVPNNode.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypeTrafficMode: FfiConverterRustBuffer<TrafficMode?> {
    override fun read(buf: ByteBuffer): TrafficMode? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeTrafficMode.read(buf)
    }

    override fun allocationSize(value: TrafficMode?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeTrafficMode.allocationSize(value)
        }
    }

    override fun write(value: TrafficMode?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeTrafficMode.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceString: FfiConverterRustBuffer<List<kotlin.String>> {
    override fun read(buf: ByteBuffer): List<kotlin.String> {
        val len = buf.getInt()
        return List<kotlin.String>(len) {
            FfiConverterString.read(buf)
        }
    }

    override fun allocationSize(value: List<kotlin.String>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterString.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<kotlin.String>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterString.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeVPNNode: FfiConverterRustBuffer<List<VpnNode>> {
    override fun read(buf: ByteBuffer): List<VpnNode> {
        val len = buf.getInt()
        return List<VpnNode>(len) {
            FfiConverterTypeVPNNode.read(buf)
        }
    }

    override fun allocationSize(value: List<VpnNode>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeVPNNode.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<VpnNode>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeVPNNode.write(it, buf)
        }
    }
} fun `add`(`a`: kotlin.UInt, `b`: kotlin.UInt): kotlin.UInt {
            return FfiConverterUInt.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_shadowmesh_core_fn_func_add(
        FfiConverterUInt.lower(`a`),FfiConverterUInt.lower(`b`),_status)
}
    )
    }
    

    @Throws(ShadowMeshException::class) fun `createVpnManager`(`settings`: UserSettings): VpnManager {
            return FfiConverterTypeVPNManager.lift(
    uniffiRustCallWithError(ShadowMeshException) { _status ->
    UniffiLib.INSTANCE.uniffi_shadowmesh_core_fn_func_create_vpn_manager(
        FfiConverterTypeUserSettings.lower(`settings`),_status)
}
    )
    }
    

    @Throws(ShadowMeshException::class) fun `generateWireguardKeys`(): List<kotlin.String> {
            return FfiConverterSequenceString.lift(
    uniffiRustCallWithError(ShadowMeshException) { _status ->
    UniffiLib.INSTANCE.uniffi_shadowmesh_core_fn_func_generate_wireguard_keys(
        _status)
}
    )
    }
    
 fun `getDefaultUserSettings`(): UserSettings {
            return FfiConverterTypeUserSettings.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_shadowmesh_core_fn_func_get_default_user_settings(
        _status)
}
    )
    }
    
 fun `getMockNodes`(): List<VpnNode> {
            return FfiConverterSequenceTypeVPNNode.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_shadowmesh_core_fn_func_get_mock_nodes(
        _status)
}
    )
    }
    
 fun `getPersistentDeviceId`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_shadowmesh_core_fn_func_get_persistent_device_id(
        _status)
}
    )
    }
    

    @Throws(ShadowMeshException::class) fun `solvePow`(`challenge`: PoWChallenge): PoWSolution {
            return FfiConverterTypePoWSolution.lift(
    uniffiRustCallWithError(ShadowMeshException) { _status ->
    UniffiLib.INSTANCE.uniffi_shadowmesh_core_fn_func_solve_pow(
        FfiConverterTypePoWChallenge.lower(`challenge`),_status)
}
    )
    }
    


