pub mod direct;
pub mod group;
pub mod hysteria;
pub mod ikev2;
pub mod openvpn;
pub mod registry;
pub mod shadowsocks;
pub mod trojan;
pub mod vmess;
pub mod wireguard;

pub use direct::DirectOutbound;
pub use group::{OutboundGroup, SelectionStrategy};
pub use hysteria::HysteriaOutbound;
pub use ikev2::Ikev2Outbound;
pub use openvpn::OpenvpnOutbound;
pub use registry::OutboundRegistry;
pub use shadowsocks::ShadowsocksOutbound;
pub use trojan::TrojanOutbound;
pub use vmess::{VlessOutbound, VmessOutbound};
pub use wireguard::WireguardOutbound;
