import { vi } from "vitest";
import type { ElectronAPI } from "../../types/shadowmesh-api";

/** Minimal ElectronAPI mock for renderer tests (type-safe, no `any`). */
export function createTestElectronAPI(
  overrides: Partial<ElectronAPI> = {},
): ElectronAPI {
  const resolved = <T,>(value: T) => vi.fn().mockResolvedValue(value);
  const defaults: ElectronAPI = {
    getNativeVersion: resolved("1.0.0"),
    getMachineId: resolved("test-machine-id"),
    startPasskeyAuth: resolved({ success: true }),
    closeApp: vi.fn(),
    minimizeApp: vi.fn(),
    connectVPN: resolved({ success: true }),
    disconnectVPN: resolved({ success: true }),
    getVPNStatus: resolved({ connected: false, state: "disconnected" }),
    startObfuscation: resolved({ success: true }),
    stopObfuscation: resolved({ success: true }),
    getObfuscationStatus: resolved({ running: false }),
    startSingBox: resolved({ success: true }),
    stopSingBox: resolved({ success: true }),
    getSingBoxStatus: resolved({ running: false }),
    testSingBox: resolved({ success: true, latency: 42 }),
    enableSmartFallback: resolved({ success: true }),
    disableSmartFallback: resolved({ success: true }),
    getSmartFallbackStatus: resolved({
      enabled: false,
      wg_config_path: "",
      singbox_config_path: "",
      check_interval_sec: 30,
      handshake_timeout_sec: 10,
      auto_switch: true,
      current_mode: "wireguard",
    }),
    pingServer: resolved(10),
    generateKeys: resolved(["priv", "pub"]),
    solvePoW: resolved("solution"),
    getBestNode: resolved(null),
    getPreferredMode: resolved("speed"),
    enableKillSwitch: resolved({ success: true }),
    disableKillSwitch: resolved({ success: true }),
    panicWipe: resolved({ success: true }),
    setDuressPin: resolved(true),
    getDuressPin: resolved(null),
    getTrafficStats: resolved({
      connected: false,
      status: "disconnected",
      recv_bps: 0,
      sent_bps: 0,
      total_recv: 0,
      total_sent: 0,
      totalBytes: 0,
      monthlyBytes: 0
    }),
    getSecurityEvents: resolved([]),
    getLogs: resolved([]),
    getIdentityInfo: resolved({
      device_id: "test-device",
      session_id: "test-session",
      plan: "Solo",
      expires_at: null,
    }),
    logout: resolved(undefined),
    getNetworkReport: resolved({
      network_type: "WiFi",
      local_ip: null,
      gateway: null,
      dns_servers: [],
      signal_strength: null,
      ssid: null,
      is_vpn_active: false,
    }),
    runFullSpeedTest: resolved({
      download_bps: 0,
      upload_bps: 0,
      latency_ms: 0,
      jitter_ms: 0,
    }),
    encryptPairingData: resolved([]),
    decryptPairingData: resolved([]),
    getQuantumParams: resolved({ mtu: 1420, tcp_mss: 1380 }),
    verifyCoreIntegrity: resolved(true),
    setAutostart: resolved(undefined),
    onDeepLinkReceived: vi.fn(),
    onTriggerConnect: vi.fn(),
    enableCamouflage: resolved(true),
    disableCamouflage: resolved(true),
    getCamouflageStatus: resolved(false),
    setSplitTunnel: resolved({ success: true }),
    onCamouflageToggled: vi.fn(),
    onVPNStatusChanged: vi.fn(),
    onTrafficStatsChanged: vi.fn(),
    onDaemonStatusChanged: vi.fn(),
    onObfuscationStatusChanged: vi.fn(),
    onSingBoxStatusChanged: vi.fn(),
    onUpdateAvailable: vi.fn(),
    onUpdateDownloaded: vi.fn(),
    onDownloadProgress: vi.fn(),
    setSecureToken: resolved(true),
    getSecureToken: resolved(null),
    removeSecureToken: resolved(true),
  };
  return { ...defaults, ...overrides };
}
